version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: fg run-dashboard
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
